"""add a table for prices on services

Revision ID: bdfac72a27ce
Revises: 1aa401363818
Create Date: 2025-01-17 10:01:11.325976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdfac72a27ce'
down_revision: Union[str, None] = '1aa401363818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('price', postgresql.MONEY(), nullable=True))
    op.drop_column('prices', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('prices', 'price')
    # ### end Alembic commands ###
